### ISSUE TITLE
What providers are you going to support?

### ISSUE THREAD

**Issue by aloisdg** [omansak/libvideo#12]
Hello,

I saw in the code:

> https://vimeo.com/131417856

After Youtube and Vimeo, who's next? :)

Cheers

**Comment by jamesqo** [comment]
Hi @aloisdg! I'm thinking maybe one of the websites listed [here](http://keepvid.com/), e.g. Vine. However, I may be doing it in another library, since I think it's better to keep focus on YouTube for now. Most of the code here is already YouTube-specific, so it would be kinda hard to add another platform at the moment.

**Comment by aloisdg** [comment]
It would be nice to write an Interface and let any provider works with it, wouldn't it?

**Comment by jamesqo** [comment]
@aloisdg Just refactored the codebase to be a lot less coupled to YouTube (7dadee8), so I may revive Vimeo support soon. I'll keep you updated.

**Comment by chukwu** [comment]
Is Vimeo supported now? Can't find it on the changelog
