### ISSUE TITLE
Video quality

### ISSUE THREAD

**Issue by WandresR** [omansak/libvideo#162]
Hello.
How can I download video in 480 and 1080 quality using libvideo ?
the code:
var video = YouTube.Default.GetAllVideos(textBox1.Text).First(v => v.Resolution == 480);  File.WriteAllBytes(@"D:\" + video.FullName, video.GetBytes());
 does not work.
I get 480 quality video but no sound.
1080 quality video cannot be downloaded.
I can download only 360 and 720.
Help required.

**Comment by emanueltilly** [comment]
I am too having issues with getting higher than 360 quality. Following.

**Comment by SulfuricAcidH2SO4** [comment]
Unfortunately the problem is from YouTube because it won't let you download anything with a resolution higher than 360p, you'll have to download audio and video separately then merge them together using FFMPEG or something.

**Comment by WandresR** [comment]
In this case, how can I download video and audio separately? The problem is that I can’t download 480 and 1080 video. The video does not load. Video with a resolution of 480 takes a very long time to load and the process takes a lot of memory. Video with a resolution of 1080 does not load, Application Crash!

**Comment by SulfuricAcidH2SO4** [comment]
You download once the video at your desired quality then download it once more at the lowest resolution. When you write the bytes you just need to change the format you're saving it in. For example if you want only the audio, you download it normally then save it as .mp3 file. About the load time it seems pretty strange to me since I've never experienced anything similar. Furthermore, this library doesn't seem to be supported anymore so i suggest trying and looking for an alternative, I'm having trouble downloading certain youtube videos
