### ISSUE TITLE
Terms of Service of Youtube

### ISSUE THREAD

**Issue by ambr-kobayashi** [omansak/libvideo#163]
Hello.
I'd like to use this library for own production.
Before using this library, I 'd like you to make sure about terms of service of Youtube( https://www.youtube.com/static?gl=US&template=terms ).

In the Permission and Restriction section, the following sentences are described.
```
The following restrictions apply to your use of the Service. You are not allowed to:

access, reproduce, download, distribute, transmit, broadcast, display, sell, license, alter, modify or otherwise use any part of the Service or any Content except: (a) as expressly authorized by the Service; or (b) with prior written permission from YouTube and, if applicable, the respective rights holders;
```

Downloading Youtube videos seem to be prohibited, however, You said "clean way to download YouTube videos" on NuGet web  page(https://www.nuget.org/packages/VideoLibrary).

So, please let me know why this library can provide 'clean way to download youtube videos'.

Thank you.

**Comment by Donaut** [comment]
For any real applications the only way to download youtube videos is by registering your service in the google credentials page. But this has their own drawbacks like there are a limit how much you can downloads(you need to pay if you want more) and using google credentials for small projects where are no organization is totally unnecesary. This libary is just like a Webrowser without a window (you just simply open Youtube and parse the datas from the HTML content). You shouldnt use this libary in real projects because its guaranteed to not work every single time when there is a change in the site.

**Comment by omansak** [comment]
this subject is not about of code so i will close this
