### ISSUE TITLE
HttpRequestException code: 403 when using Video.GetBytes()

### ISSUE THREAD

**Issue by kirigar** [omansak/libvideo#36]
I'm getting a HttpRequestException on certain videos the video I was testing it with is this one: https://www.youtube.com/watch?v=Lx2zzIkaUZQ
But I've only noticed this error with videos from this channel. (I haven't tested it a lot though)

**Comment by ATypescriptEnjoyer** [comment]
Hmm, my music bot's using this api and it ran the song, although my music bot uses a try and catch for playing songs. Wrap your code in a try catch, and have the catch rerun the method with the song, it should work. If you need more help visit my TS3MusicBot, since it also uses the code and is all commented.

**Comment by kirigar** [comment]
Yeah, it works also works for me now. No idea what was going on then
